// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: wails.proto

package wailspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                        // e.g. "pkg.Struct.Method"
	ArgsProto     []byte                 `protobuf:"bytes,2,opt,name=args_proto,json=argsProto,proto3" json:"args_proto,omitempty"` // optional protobuf-encoded args blob (reserved for future)
	ArgsJson      string                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`    // fallback JSON-encoded args (matches current Wails JSON payload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_wails_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wails_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_wails_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetArgsProto() []byte {
	if x != nil {
		return x.ArgsProto
	}
	return nil
}

func (x *CallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ResultProto   []byte                 `protobuf:"bytes,2,opt,name=result_proto,json=resultProto,proto3" json:"result_proto,omitempty"` // optional protobuf-encoded result
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`    // fallback JSON-encoded result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_wails_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wails_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_wails_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallResponse) GetResultProto() []byte {
	if x != nil {
		return x.ResultProto
	}
	return nil
}

func (x *CallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type EventSubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // event name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscribe) Reset() {
	*x = EventSubscribe{}
	mi := &file_wails_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscribe) ProtoMessage() {}

func (x *EventSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_wails_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscribe.ProtoReflect.Descriptor instead.
func (*EventSubscribe) Descriptor() ([]byte, []int) {
	return file_wails_proto_rawDescGZIP(), []int{2}
}

func (x *EventSubscribe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventNotify) Reset() {
	*x = EventNotify{}
	mi := &file_wails_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotify) ProtoMessage() {}

func (x *EventNotify) ProtoReflect() protoreflect.Message {
	mi := &file_wails_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotify.ProtoReflect.Descriptor instead.
func (*EventNotify) Descriptor() ([]byte, []int) {
	return file_wails_proto_rawDescGZIP(), []int{3}
}

func (x *EventNotify) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventNotify) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_wails_proto protoreflect.FileDescriptor

const file_wails_proto_rawDesc = "" +
	"\n" +
	"\vwails.proto\x12\bwails.v2\"a\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"args_proto\x18\x02 \x01(\fR\targsProto\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"h\n" +
	"\fCallResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12!\n" +
	"\fresult_proto\x18\x02 \x01(\fR\vresultProto\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\"$\n" +
	"\x0eEventSubscribe\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\vEventNotify\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson2\x88\x01\n" +
	"\fWailsService\x125\n" +
	"\x04Call\x12\x15.wails.v2.CallRequest\x1a\x16.wails.v2.CallResponse\x12A\n" +
	"\fStreamEvents\x12\x18.wails.v2.EventSubscribe\x1a\x15.wails.v2.EventNotify0\x01B5Z3github.com/wailsapp/wails/v2/internal/proto;wailspbb\x06proto3"

var (
	file_wails_proto_rawDescOnce sync.Once
	file_wails_proto_rawDescData []byte
)

func file_wails_proto_rawDescGZIP() []byte {
	file_wails_proto_rawDescOnce.Do(func() {
		file_wails_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wails_proto_rawDesc), len(file_wails_proto_rawDesc)))
	})
	return file_wails_proto_rawDescData
}

var file_wails_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wails_proto_goTypes = []any{
	(*CallRequest)(nil),    // 0: wails.v2.CallRequest
	(*CallResponse)(nil),   // 1: wails.v2.CallResponse
	(*EventSubscribe)(nil), // 2: wails.v2.EventSubscribe
	(*EventNotify)(nil),    // 3: wails.v2.EventNotify
}
var file_wails_proto_depIdxs = []int32{
	0, // 0: wails.v2.WailsService.Call:input_type -> wails.v2.CallRequest
	2, // 1: wails.v2.WailsService.StreamEvents:input_type -> wails.v2.EventSubscribe
	1, // 2: wails.v2.WailsService.Call:output_type -> wails.v2.CallResponse
	3, // 3: wails.v2.WailsService.StreamEvents:output_type -> wails.v2.EventNotify
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wails_proto_init() }
func file_wails_proto_init() {
	if File_wails_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wails_proto_rawDesc), len(file_wails_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wails_proto_goTypes,
		DependencyIndexes: file_wails_proto_depIdxs,
		MessageInfos:      file_wails_proto_msgTypes,
	}.Build()
	File_wails_proto = out.File
	file_wails_proto_goTypes = nil
	file_wails_proto_depIdxs = nil
}
